Fix

diff --git a/git-plow-feature b/git-plow-feature
--- a/git-plow-feature
+++ b/git-plow-feature
@@ -3,6 +3,10 @@
 cmd_feature() {
 
   BRANCH=$(git rev-parse --abbrev-ref HEAD)
+  if ! echo $BRANCH | grep --quiet -E '^feature/'; then
+    echo "Cannot find feature name in current branch $BRANCH"
+    exit 1
+  fi
   NAME=$(echo $BRANCH | sed 's/.*\///')
   IAMADMIN=$(i_am_admin)
 
diff --git a/git-plow-hotfix b/git-plow-hotfix
--- a/git-plow-hotfix
+++ b/git-plow-hotfix
@@ -3,7 +3,11 @@
 cmd_hotfix() {
 
   BRANCH=$(git rev-parse --abbrev-ref HEAD)
-  NAME=$(echo $BRANCH | sed 's/.*\///')
+  if ! echo $BRANCH | grep --quiet -E '^hotfix/'; then
+    echo "Cannot find hotfix name in current branch $BRANCH"
+    exit 1
+  fi
+  NAME=$(echo $BRANCH | sed 's/hotfix\///')
   IAMADMIN=$(i_am_admin)
 
   local action="$1"; shift
